---
title: "Beer app"
author: "Austin Webb"
date: '2022-07-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```




```{r}
library(shiny)
library(ggplot2)

```

```{r}

#### UI ---------------------------------------------------------

ui_upload <- sidebarLayout(
 
  # sidebar ---------------------------------------------------------
   
  sidebarPanel(
    fileInput("file", "Data", buttonLabel = "Upload..."),
    textInput("delim", "Delimiter (leave blank to guess)", ""),
    numericInput("rows", "Rows to preview", 5, min = 1),
    hr(),
    
    checkboxInput("NAs", "Remove NAs?"),
    
    selectInput('state', label=h3('Choose State'),
                choices=list("All" = "All", 'Alabama'='AL', 'Alaska'='AK', 
                             'Arizona'='AZ', 'Arkansas'='AR', 'California'='CA', 
                             'Colorado'='CO', 'Connecticut'='CT', 'Delaware'='DE', 
                             'Florida'='FL', 'Georgia'='GA', 'Hawaii'='HI', 
                             'Idaho'='ID', 'Illinois'='IL', 'Indiana'='IN', 
                             'Iowa'='IA', 'Kansas'='KS', 'Kentucky'='KY', 
                             'Louisiana'='LA', 'Maine'='ME', 'Maryland'='MD', 
                             'Massachusetts'='MA', 'Michigan'='MI', 
                             'Minnesota'='MN', 'Mississippi'='MS', 'Missouri'='MO', 
                             'Montana'='MT', 'Nebraska'='NE', 'Nevada'='NV', 
                             'New Hampshire'='NH', 'New Jersey'='NJ',
                             'New Mexico'='NM', 'New York'='NY', 'North Carolina'='NC', 
                             'North Dakota'='ND', 'Ohio'='OH', 'Oklahoma'='OK', 
                             'Oregon'='OR', 'Pennsylvania'='PA', 'Rhode Island'='RI', 
                             'South Carolina'='SC', 'South Dakota'='SD', 
                             'Tennessee'='TN', 'Texas'='TX', 'Utah'='UT', 
                             'Vermont'='VT', 'Virginia'='VA', 'Washington'='WA', 
                             'West Virginia'='WV', 'Wisconsin'='WI', 'Wyoming'='WY')),
        
    
    hr(),
    
    selectInput('select',
                label = h3('ABV or IBU'),
                choices = c('ABV', 'IBU'),
                selected = 1), 
    hr(),
    
    # Input: radio button for plot choice
    radioButtons(inputId = 'plotChoice', 'Which plot?',
                 choices = c('Histogram', 'Boxplot', 'Scatterplot')
                 ),    
    hr(),
    
    # Input: slider for number of bins
    sliderInput(inputId = 'bins',
                label = 'Number of Bins',
                min = 1,
                max = 50,
                value = 30),
    
    # regression line
    checkboxInput("Regression", "Add regression line?"),

    hr(),
    fluidRow(column(3, verbatimTextOutput('value')))
  ),

  
  # main ---------------------------------------------------------
  mainPanel(
    h3("Beer data"),
    tableOutput("preview1"),
    h3("Clean data"),
    tableOutput("preview3"),
  
  # Output: histogram
    plotOutput('distPlot')
  )
)






ui_download <- fluidRow(
  column(width = 12, downloadButton("download", class = "btn-block"))
)

ui <- fluidPage(
  ui_upload,
  ui_download
)




#### SERVER ---------------------------------------------------------

server <- function(input, output, session) {
  
  # Upload ---------------------------------------------------------
  raw <- reactive({
    req(input$file)
    delim <- if (input$delim == "") NULL else input$delim
    vroom::vroom(input$file$datapath, delim = delim)
  })
  output$preview1 <- renderTable(head(raw(), input$rows))
  
 
  # Clean ----------------------------------------------------------
  tidied <- reactive({
    out <- raw()
    if (input$NAs) {
      names(out) <- na.omit(out)
    }
    
  })

  output$preview3 <- renderTable(head(tidied(), input$rows))
  
  # histogram ----------------------------------------------------------  
  
  output$distPlot <- renderPlot({

    beer <- tidied()
    
    # beer by state df    

    beers <- if(input$state == 'All'){
      tidied()
    } else {
      filter(tidied(), State == input$state)
    }
          
      
      
    if (input$plotChoice == "Histogram") {

      if(input$select == 'ABV') {
        x <- beers$ABV
        
        bins <- seq(min(x), 
                    max(x), 
                    length.out = input$bins + 1)
        
        hist(x, 
             breaks = bins,
             col = 'red',
             border = 'blue',
             xlab = 'ABV',
             main = 'Histogram of ABV')
      } # end the if abv 
      
      if(input$select == 'IBU') {
        x <- beers$IBU
        
        bins <- seq(min(x), 
                    max(x), 
                    length.out = input$bins + 1)
        
        hist(x, 
             breaks = bins,
             col = 'red',
             border = 'blue',
             xlab = 'IBU',
             main = 'Histogram of IBU')
        
      } # end the if ibu
    } # end the if histogram
    
    else if (input$plotChoice == "Boxplot") {

      if(input$select == 'ABV') {
        
        ggplot(beers, aes(x = ABV)) + 
          geom_boxplot(fill = 'red', 
                       color = 'blue') +
          ggtitle('ABV Distribution')
      } # end the if ibu
      
      else if(input$select == 'IBU') {
        
        ggplot(beers, aes(x = IBU)) + 
          geom_boxplot(fill = 'red', 
                       color = 'blue') +
          ggtitle('IBU Distribution')
        
      } # end the if abv
      
    } # end the if boxplot 
    
    
    else if (input$plotChoice == "Scatterplot") {
      
      if(input$select == 'ABV') {
        
        if (input$Regression) {
          
          ggplot(beers, aes(x = ABV, y = IBU)) + 
          geom_point(color = 'red') +
          ggtitle('ABV vs IBU') +
          geom_smooth(method = lm, 
                      color = 'blue', 
                      fill = 'blue')  
        } # end regression if statement
        
        
        else {
          ggplot(beers, aes(x = ABV, y = IBU)) + 
          geom_point(color = 'red') +
          ggtitle('ABV vs IBU')
        } # end else regression statement
      } # end the if abv
      
      else if(input$select == 'IBU') {
        
        if (input$Regression) {
          
          ggplot(beers, aes(x = IBU, y = ABV)) + 
          geom_point(color = 'red') +
          ggtitle('IBU vs ABV') +
          geom_smooth(method = lm, 
                      color = 'blue', 
                      fill = 'blue')  
        } # end regression if statement

        else {
          ggplot(beers, aes(x = IBU, y = ABV)) + 
          geom_point(color = 'red') +
          ggtitle('IBU vs ABV') 
        } # end else regression statement
      } # end the if ibu
    } # end the if scatterplot
    
  }) # end the render plot
  
  
  
  
  
  
 
 
  # Download -------------------------------------------------------
  output$download <- downloadHandler(
    filename = function() {
      paste0(tools::file_path_sans_ext(input$file$name), ".tsv")
    },
    content = function(file) {
      vroom::vroom_write(tidied(), file)
    }
  )
  
}


shinyApp(ui, server)

```

