---
title: "Unit 2"
author: "Austin Webb"
date: '2022-07-13'
output: html_document
---


## UNIT 2 R Quick Start / Scatterplot, histogram and bar plot.R

### Remember Previous Plots from Unit 1
### Let's redo them using ggplot2!

Scatterplot
```{r}
#install.packages("ggplot2")
library(ggplot2)
library(tidyverse)

#Iris Scatterplot
ggplot(data = iris, mapping = aes(x = Sepal.Length, y = Petal.Length)) + geom_point()

#With pipe!  %>% = "and then"
iris %>% ggplot(aes(x = Sepal.Length,y = Petal.Length)) + geom_point() #Labels but not TITLE! AHHH!!!!

iris %>% ggplot(aes(x = Sepal.Length,y = Petal.Length)) + geom_point() + ggtitle("City MPG v. Highway MPG")

# You Try It! (mpg)
# plot (scatter plot) city mile per gallon (y) versus highway miles per gallon (x).

mpg %>% ggplot(aes(x = hwy, y = cty)) + geom_point() + ggtitle("City MPG v. Highway MPG")
```


Histogram
```{r}
#Iris histogram
iris %>% ggplot(aes(x = Petal.Length)) + geom_histogram() + ggtitle("Histogram of Petal Length")


# You Try It!  investigate the distribuion of the city miles per gallon variable for compact cars.  

mpg[mpg$class == "compact",] %>% ggplot(aes(x = cty)) + geom_histogram()

#You Try It!  No compare the distribution of cty for compact cars to that of SUVs.  

mpg[mpg$class == "suv",] %>% ggplot(aes(x = cty)) + geom_histogram()

# You Try It Bonus!  In order to compare the distributions, we should put them on the same scale.
# Research how to change the scale!

mpg[mpg$class == "compact",] %>% ggplot(aes(x = cty)) + geom_histogram() + coord_cartesian(xlim = c(0, 50)) 
```

Boxplot
```{r}
#Iris Boxplot
iris %>% ggplot(aes(x = Species, y = Petal.Length)) + geom_boxplot()


# You Try It!

#Find a box plot from the mpg dataset of the city mpg versus the class of car.
mpg %>% ggplot(aes(x = class, y = cty)) + geom_boxplot() + ggtitle("Boxplot of City MPG v. Class")
```



### Bar plot with mpg and class
```{r}
#With base barplot
summary(mpg$class)

mpg$classFact = as.factor(mpg$class)
head(mpg)
summary(mpg$classFact)

barplot(summary(mpg$classFact))

# With ggplot /  geom_bar()
mpg %>% ggplot(aes(x = class)) + geom_bar() + ggtitle("Distribution of Class")
```

## Bar plot with toy Student and Math Experience data
```{r}
#With base barplot
age = c(22,21,24,19,20,23)
yrs_math_ed = c(4,5,2,5,3,5)
names = c("Mary","Martha","Kim","Kristen","Amy","Sam")
subject = c("English","Math","Sociology","Math","Music","Dance")

df3 = data.frame(Age = age, Years = yrs_math_ed, Name = names, Subject = subject)

barplot(df3$Years, names.arg = df3$Name)


# With ggplot /  geom_bar()   Where does Years go? We will come back to this!
df3 %>% ggplot(aes(x = Name)) + geom_bar() + ggtitle("Distribution of Class")

df3 %>% ggplot(aes(x = Name, y = Years)) + geom_bar(stat = "identity") + ggtitle("Distribution of Class")

df3 %>% ggplot(aes(x = Name, y = Years)) + geom_col() + ggtitle("Distribution of Class")



# You Try It!
# Iris Data:  Create a Barplot of how many of each Species are in the study.

iris %>% ggplot() + geom_bar(aes(x = Species))

# You Try it Bonus: Create a dataframe of how you rank (scale of 1(least) to 10 (best)) traveling by car, train, plane, boat (ship), and bike.

travelDF = data.frame(type = c("car", "train", "plane", "boat", "bike"), rank = c(7,9,8,5,6))

travelDF %>% ggplot(aes(x = type, y = rank)) + geom_col() + ggtitle("Tavel Ranking")
```



## AES
### AES: X and Y
```{r}
mpg %>% 
ggplot(mapping = aes(x = hwy, y = cty)) +
geom_point()

mpg %>% 
ggplot(mapping = aes(x = hwy)) + 
geom_histogram()

mpg %>% 
ggplot(mapping = aes(x = class)) + 
geom_bar()

```

### AES: color
```{r}
mpg %>% ggplot(aes(x = hwy, y = cty,color = mpg$drv)) + geom_point()

# color = "blue" is not a mapping of a variable
mpg %>% ggplot(aes(x = hwy, y = cty, color = "blue")) + 
geom_point()

#note that color is not in an ”aes”
# function we are setting them manually.
mpg %>% ggplot(aes(x = hwy, y = cty)) + 
geom_point(color = "blue")

# note now we are ”mapping” fill to a variable (drv).
mpg[mpg$class == "compact",] %>% ggplot(aes(x = cty, fill = drv)) + 
geom_histogram(color = "black") 

#note that fill and color are not in an ”aes” function we are setting them manually.
# We are not “mapping” variables to colors… rather just setting the color.  
mpg[mpg$class == "compact",] %>% ggplot(aes(x = cty)) + 
geom_histogram(fill = "blue", color = "black") 

# note now we are ”mapping” fill to a variable (drv).
mpg %>% ggplot(aes(x = class, y = cty,fill = drv)) + geom_boxplot(color = "blue")

#note that fill and color are not in an ”aes” function we are setting them manually.
# We are not “mapping” variables to colors… rather just setting the color.  
mpg %>% ggplot(aes(x = class, y = cty)) + geom_boxplot(color = "blue", fill = "black") 

```


### AES: size
```{r}
mpg %>% ggplot(aes(x = hwy, y = cty, size = mpg$displ)) + geom_point()

```


### AES: size
```{r}
mpg %>% ggplot(aes(x = hwy, y = cty, size = mpg$displ)) + geom_point()

```


### AES: size
```{r}
mpg %>% ggplot(aes(x = hwy, y = cty, size = mpg$displ)) + geom_point()

```


